#!/usr/bin/env ruby

require 'gridlock_ci'
require 'optparse'

def run_command
  options = {}

  OptionParser.new do |opts|
    opts.banner = 'Usage: gridlock_ci run [flags]'

    opts.on('--run_id RUN_ID', 'Run ID to associate with [required]') do |r|
      options[:run_id] = r
    end

    opts.on('--run_attempt RUN_ATTEMPT', 'Run attempt number [required]') do |r|
      options[:run_attempt] = r
    end

    opts.on('--junit-output FILE', 'Export rspec results in junit format to FILE') do |r|
      options[:junit_output] = r
    end

    opts.on('--rspec \'rspec-options\'', 'Options to pass to rspec') do |r|
      options[:rspec] = r
    end
  end.parse!

  options
end

def enqueue_command
  options = {}

  OptionParser.new do |opts|
    opts.banner = 'Usage: gridlock_ci enqueue [flags] [rspec-args]'

    opts.on('--run_id RUN_ID', 'Run ID to associate with [required]') do |o|
      options[:run_id] = o
    end

    opts.on('--run_attempt RUN_ATTEMPT', 'Run attempt number [required]') do |o|
      options[:run_attempt] = o
    end

    opts.on('--spec-glob GLOB', 'Glob to find specs [default: spec/**/*_spec.rb]') do |o|
      options[:spec_glob] = o
    end

    opts.on('--specs SPEC_FILES', 'List of specs to enqueue delimited by spaces. [ex: "spec/foo_spec.rb spec/bar_spec.rb"]') do |o|
      options[:specs] = o
    end
  end.parse!

  options
end

def upload_results_command
  options = {}

  OptionParser.new do |opts|
    opts.banner = 'Usage: gridlock_ci upload_results [flags]'

    opts.on('--run_id RUN_ID', 'Run ID to associate with [required]') do |o|
      options[:run_id] = o
    end

    opts.on('--run_attempt RUN_ATTEMPT', 'Run attempt number [required]') do |o|
      options[:run_attempt] = o
    end

    opts.on('--file_path FILE_PATH', 'Path to results file [required]') do |o|
      options[:file_path] = o
    end
  end.parse!

  options
end

global = OptionParser.new do |opts|
  opts.banner = 'Usage: gridlock_ci [command] [options]'
  opts.separator ''
  opts.separator "Commands:\n run\n enqueue\n upload_results"
end

global.order!
command = ARGV.shift

case command
when 'run'
  opts = run_command
  rspec_opts = opts[:rspec] ? opts[:rspec].split : []
  GridlockCi::Runner.new(opts[:run_id], opts[:run_attempt]).run(rspec_opts: rspec_opts,
                                                                junit_output: opts[:junit_output])
when 'enqueue'
  opts = enqueue_command

  specs = if opts[:specs]
            opts[:specs].split
          else
            Dir.glob(opts[:spec_glob] || 'spec/**/*_spec.rb')
          end

  GridlockCi::Client.new(opts[:run_id], opts[:run_attempt]).send_specs(specs)
when 'upload_results'
  opts = upload_results_command

  GridlockCi::Client.new(opts[:run_id], opts[:run_attempt]).upload_results(opts[:file_path])
else
  puts 'Command not found'
  exit 1
end
